# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt4_simple.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(674, 352)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Purisa"))
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.nama_saya = QtGui.QLineEdit(self.centralwidget)
        self.nama_saya.setGeometry(QtCore.QRect(360, 30, 113, 27))
        self.nama_saya.setObjectName(_fromUtf8("nama_saya"))
        self.port = QtGui.QLineEdit(self.centralwidget)
        self.port.setGeometry(QtCore.QRect(360, 80, 113, 27))
        self.port.setObjectName(_fromUtf8("port"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 10, 111, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.btnSend = QtGui.QPushButton(self.centralwidget)
        self.btnSend.setGeometry(QtCore.QRect(280, 270, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Serif Thai"))
        self.btnSend.setFont(font)
        self.btnSend.setObjectName(_fromUtf8("btnSend"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 60, 111, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.ip_dir = QtGui.QLineEdit(self.centralwidget)
        self.ip_dir.setGeometry(QtCore.QRect(360, 130, 113, 27))
        self.ip_dir.setText(_fromUtf8(""))
        self.ip_dir.setReadOnly(True)
        self.ip_dir.setObjectName(_fromUtf8("ip_dir"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 110, 111, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.edChat = QtGui.QTextEdit(self.centralwidget)
        self.edChat.setGeometry(QtCore.QRect(50, 270, 221, 31))
        self.edChat.setObjectName(_fromUtf8("edChat"))
        self.btn_look_ip = QtGui.QPushButton(self.centralwidget)
        self.btn_look_ip.setGeometry(QtCore.QRect(360, 160, 111, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Serif Armenian"))
        self.btn_look_ip.setFont(font)
        self.btn_look_ip.setObjectName(_fromUtf8("btn_look_ip"))
        self.look_ip = QtGui.QPlainTextEdit(self.centralwidget)
        self.look_ip.setGeometry(QtCore.QRect(360, 190, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.look_ip.setFont(font)
        self.look_ip.setReadOnly(True)
        self.look_ip.setObjectName(_fromUtf8("look_ip"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 270, 111, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(430, 290, 111, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(530, 10, 71, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 10, 111, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.online = QtGui.QListWidget(self.centralwidget)
        self.online.setGeometry(QtCore.QRect(480, 30, 181, 221))
        self.online.setObjectName(_fromUtf8("online"))
        self.edHasil = QtGui.QPlainTextEdit(self.centralwidget)
        self.edHasil.setGeometry(QtCore.QRect(50, 30, 291, 231))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.edHasil.setFont(font)
        self.edHasil.setReadOnly(True)
        self.edHasil.setObjectName(_fromUtf8("edHasil"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 674, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "UDP Chat Client", None))
        self.nama_saya.setText(_translate("MainWindow", "umar", None))
        self.port.setText(_translate("MainWindow", "3393", None))
        self.label.setText(_translate("MainWindow", "my name is     :", None))
        self.btnSend.setText(_translate("MainWindow", "Send", None))
        self.label_2.setText(_translate("MainWindow", "port direction :", None))
        self.label_3.setText(_translate("MainWindow", "IP direction     :", None))
        self.btn_look_ip.setText(_translate("MainWindow", "turn on chat", None))
        self.label_4.setText(_translate("MainWindow", "created by :", None))
        self.label_5.setText(_translate("MainWindow", "GOmandiri6 team", None))
        self.label_8.setText(_translate("MainWindow", "now active :", None))
        self.label_7.setText(_translate("MainWindow", "messages :", None))

